apiVersion: v1
kind: ServiceAccount
metadata:
  name: omnifleet-prometheus
  namespace: omnifleet
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: omnifleet-prometheus
    prometheus: omnifleet-prometheus
  name: omnifleet-prometheus
  namespace: omnifleet
spec:
  alerting:
    alertmanagers:
      - name: promstack-kube-prometheus-alertmanager
        namespace: observability
        port: web
        pathPrefix: /
        apiVersion: v2
  image: quay.io/prometheus/prometheus
  logLevel: info
  paused: false
  replicas: 1
  retention: 1d
  routePrefix: /
  ruleSelector:
    matchLabels:
      prometheus: omnifleet-prometheus
  serviceAccountName: omnifleet-prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      prometheus: omnifleet
  serviceMonitorSelector:
    matchLabels:
      env: dev

---
apiVersion: v1
kind: Service
metadata:
  name: omnifleet-prometheus
  namespace: omnifleet
spec:
  clusterIP: None
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: omnifleet-prometheus
  type: ClusterIP
